---
- hosts: localhost
  connection: local
  vars:
    user: mabl
    location: northeurope
    virtual_network_name: "webserver_{{ user }}"
    subnet: Webserver
    resource_group: "webserver_{{ user }}"
    domain_sub: "domain{{ user }}"
    ssh_public_key: "{{lookup('file', '~/.ssh/id_rsa.pub') }}"

  tasks:
  - name: Create a virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ virtual_network_name }}"
      address_prefixes_cidr: "10.99.0.0/16"
      tags:
          solution: "webserver_{{ user }}"
          delete: ansibletraining

  - name: Create a subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      virtual_network_name: "{{ virtual_network_name }}"
      name: "{{ subnet }}"
      address_prefix_cidr: "10.99.0.0/24"
 - name: Create a VM webserver
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "webserver"
      os_type: Linux
      admin_username: "{{ user }}"
      ssh_password_enabled: false
      ssh_public_keys:
        - path: "/home/{{ user }}/.ssh/authorized_keys"
          key_data: "{{ ssh_public_key }}"
      managed_disk_type: Standard_LRS
      state: present
      image:
        offer: RHEL
        publisher: RedHat
        sku: 8
        version: latest
      vm_size: Standard_A1_v2
      network_interfaces: "webserver_nic01"
      tags:
          solution: "webserver_{{ user }}"
          delete: ansibletraining

  - name: Show webserver public ip
    debug:
      msg: "{{ webserver_pub_ip.state.ip_address }}"

  - name: Add webserver to ssh known_hosts
    shell: "ssh-keyscan -t ecdsa {{ webserver_pub_ip.state.ip_address }}  >> /home/{{ user }}/.ssh/known_hosts"

